ktor:
    application:
        modules:
            - jp.ac.it_college.std.s24016.kotlin.ktor.book.manager.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password